services:

  sub-postgres:
    image: postgres:18.4-bookworm
    container_name: sub-env-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  sub-postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
    command: 
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@sub-postgres:5432/${POSTGRES_DB}?sslmode=disable"
      - "up"
    depends_on:
      sub-postgres:
        condition: service_healthy
    restart: "no" 



  sub-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sub-env-app
    depends_on:
      sub-postgres:
        condition: service_healthy
      sub-postgres-migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - POSTGRES_HOST=sub-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=/app/logs
    volumes:
      - ${PROJECT_ROOT}/out/logs:/app/logs 
    restart: unless-stopped